### ISSUE TITLE
Create a submodule for providing easy access to System properties

### ISSUE THREAD

**Issue by Ansh-Sarkar** [prashantsengar/ArrangePy#16]
In the Readme.md file : **What's next -> Make a complete PC suite by integrating other features -> Get info about PC health** ,
one of the future objectives of this repository has been highlighted. I would like to propose making a python module which could provide fast and easy access to details of a systems underlying architecture , ranging from disk partitions to processor count.

Such a module in my view would help future work on projects closely related to a computers underlying hardware , much more easier . The data obtained from such a module can also be used to provide statistics to the user and predict the systems health which would be a key feature to convert the project into a complete PC suite.

**Comment by Ansh-Sarkar** [comment]
I would like to work on this issue. Could you please assign it to me ?

**Comment by prashantsengar** [comment]
@Ansh-Sarkar can you please mention exactly what features you would be adding?

Have you read the contribution guide as well (specially the blog post mentioned)?

**Comment by Ansh-Sarkar** [comment]
Yes I did . Sorry for next mentioning the exact features. Will do so .

**Comment by Ansh-Sarkar** [comment]
The module should be able to provide the following data :
1. Software and Hardware info :

**Comment by Ansh-Sarkar** [comment]
1. System software and hardware info
2. First boot time stamp data
3. CPU statistics such as number of cores , percentage usage and frequency
4. Memory statistics : Used , available and total memory
5. Disk partitioning data : Number of disk partitions and total read/write operations performed on them
6. Network hardware : IP/MAC address , broadcast address and total bytes sent and received
7. GPU statistics : return the GPU id , name , manufacturer , temperature  , memory usage.

These are the main statistics / information which this module would provide access to. It requires a few extra python libraries which i will be adding to the requirements.txt file.

**Comment by prashantsengar** [comment]
Thanks for the detailed explanation!

I think you will be using `subprocess` or `psutil` to achieve this?
You can go ahead with this IMO. Make sure that you present it in a user-friendly way.
Also look at #14 by @encrypted-jpg which also does the same perhaps

**Comment by Ansh-Sarkar** [comment]
Yes @prashantsengar will be using both those libraries. #14 focuses only on a few parameters but my aim is to provide a module on which future developers can get easy access to such system data. Also may I know what user-friendly means ? Like properly commented code or something ? And sorry but what is IMO ?

**Comment by Ansh-Sarkar** [comment]
Will send the P.R. soon thank you.
