### ISSUE TITLE
A clean GUI

### ISSUE THREAD

**Issue by devsTudu** [prashantsengar/ArrangePy#18]
i can create a simple GUI for the app, assign me

**Comment by prashantsengar** [comment]
Hi @devsTudu :) I hope you have read the contribution guide and have joined the Telegram group.

Can you please let me know how are you going to do this? What is in your mind? I love to hear you out

**Comment by devsTudu** [comment]
I don't know exactly how I would do that, probably Tkinter or else alternatively, we can use a web app which will display on the browser, with all the menus and option available. 
We are cleaning the directories to look good, so we must also give a good interface for the user. I think web app will be best option as it is platform independent.

**Comment by prashantsengar** [comment]
Web app looks a cool idea 😎 Please go ahead and keep me updated
