### ISSUE TITLE
Making a cleaning suite

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/ArrangePy#2]
- [ ] Walk-through the whole PC to get info about large files
I would suggest os.walk method of os module. ([GFG](https://www.geeksforgeeks.org/os-walk-python/), [docs](https://docs.python.org/3/library/os.html))
- [ ] Find duplicate files in the PC. 
Again, uses os.walk

Create functions named get_large_files and find_duplicate. Make sure your code is modular. Put them up here and then we will see how to add them to our project.

**Comment by SANJAY729** [comment]
Can I take this issue?

**Comment by prashantsengar** [comment]
Yes sure

**Comment by Abhi-Kmr2046** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by prashantsengar** [comment]
Sure @Abhi-Kmr2046
