### ISSUE TITLE
Move from CleanPy to ArrangePy

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/ArrangePy#64]
Since we are moving from CleanPy to ArrangePy, we need to replace all the occurrences of the former with ArrangePy.

This includes all the Python files, HTML files, README, Contribution.

There is a blog post URL to my blog that also includes cleanpy but it should not be replaced as of now.

This can be easily done in VScode or any other IDE that allows you to replace occurrences across files.

**Comment by museHD** [comment]
I could help with this

**Comment by museHD** [comment]
@prashantsengar Please check out #65.
Thanks 👍🏼

**Comment by prashantsengar** [comment]
Thank you @museHD 👏
